trigger:
- main

pool:
  vmImage: windows-latest

variables:
- group: APP-SVC-EXT-KV

steps:

- script: |
    choco install armclient --source=https://chocolatey.org/api/v2/
  displayName: 'Install armclient'

- script: |
    armclient spn $(TenantId) $(ServicePrincipalId) $(ServicePrincipalKey)
  displayName: 'Install AppDynamics Extension'

