trigger:
- main

pool:
  vmImage: windows-latest

variables:
- group: APP-SVC-EXT-KV

steps:

- script: |
    choco install armclient --source=https://chocolatey.org/api/v2/
  displayName: 'Install armclient'

- script: |
    armclient spn $(TenantId) $(ServicePrincipalId) $(ServicePrincipalSecret)

    armclient put "/subscriptions/$(SubscriptionId)/resourceGroups/$(ResourceGroupName)/providers/Microsoft.Web/sites/$(AppServiceName)/siteextensions/$(ExtensionName)?api-version=2021-02-01" @payload.json

  displayName: 'Install AppDynamics Extension'

